[package]
name = "atp"
version = "0.0.1"
edition = "2021"
description = "A command line tool for the Authenticated Transfer Protocol"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }
directories = "5.0.0"
reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "macros", "fs"] }
toml = "0.7.3"
